### ISSUE TITLE
make fails when converting to C++

### ISSUE THREAD

**Issue by jalexcole** [raysan5/raylib-game-template#1]
All I did was change the compiler from gcc to g++ and change the flag -std=c99 to -std=c++17

`
alex@pop-os:~/Dropbox/dev/silver-palm-tree/src$ make
make raylib_game
make[1]: Entering directory '/home/alex/Dropbox/dev/silver-palm-tree/src'
g++ -c raylib_game.c -o raylib_game.o -Wall -std=c++17 -D_DEFAULT_SOURCE -Wno-missing-braces -s -O1 -D_DEFAULT_SOURCE -I/usr/local/include -I. -I/home/alex/Dropbox/dev/silver-palm-tree/src -I/home/alex/Dropbox/dev/silver-palm-tree/src/external -DPLATFORM_DESKTOP
raylib_game.c:25:28: error: invalid conversion from ‘int’ to ‘GameScreen’ [-fpermissive]
   25 | GameScreen currentScreen = 0;
      |                            ^
      |                            |
      |                            int
raylib_game.c: In function ‘void ChangeToScreen(int)’:
raylib_game.c:142:21: error: invalid conversion from ‘int’ to ‘GameScreen’ [-fpermissive]
  142 |     currentScreen = screen;
      |                     ^~~~~~
      |                     |
      |                     int
raylib_game.c: In function ‘void UpdateTransition()’:
raylib_game.c:189:29: error: invalid conversion from ‘int’ to ‘GameScreen’ [-fpermissive]
  189 |             currentScreen = transToScreen;
      |                             ^~~~~~~~~~~~~
      |                             |
      |                             int
raylib_game.c: At global scope:
raylib_game.c:120:13: warning: ‘void ChangeToScreen(int)’ defined but not used [-Wunused-function]
  120 | static void ChangeToScreen(int screen)
      |             ^~~~~~~~~~~~~~
make[1]: *** [Makefile:407: raylib_game.o] Error 1
make[1]: Leaving directory '/home/alex/Dropbox/dev/silver-palm-tree/src'
make: *** [Makefile:398: all] Error 2`

**Comment by raysan5** [comment]
@jalexcole that's as expected because it is a C template, not C++.
