### ISSUE TITLE
Suggestion: Move makefile and resources outside of the src folder

### ISSUE THREAD

**Issue by jalexcole** [raysan5/raylib-game-template#2]
This is more of making this a bit easier to work with and that is having the makefile at the top level of the project folder. Also would like to see the resource folder at the top level to not clutter up the src folder.

**Comment by jalexcole** [comment]
Also it would be nice to have the .o files go somewhere else instead of the src folder.

**Comment by raysan5** [comment]
@jalexcole this templates works ok for me in the current build directories configuration. I know it's not the most professional one but it's simple to work with. Maybe I review it on the future.

**Comment by anatagawa** [comment]
i think you can change some things like this

```Makefile
# Define all source files required
PROJECT_SOURCE_FILES ?= \
    raylib_game.c \
    screen_logo.c \
    screen_title.c \
    screen_options.c \
    screen_gameplay.c \
    screen_ending.c
```

by

```Makefile
SRC = src/
PROJECT_SOURCE_FILES ?= $(wildcard $(SRC)*.c $(SRC)**/*.c)
```

SRC is your source folder of all C files

and put your makefile at root project folder
