### ISSUE TITLE
Is it wise to add working directory change for compiling/debugging

### ISSUE THREAD

**Issue by snader** [raysan5/raylib-game-template#25]
I think it is a good idea to expand the readme with information about changing the working directory into $(ProjectDir)\..\..\..\src\
Just so that the .exe that is being debugged can find the resrouces properly. I ended up figuring this out myself.. took me an hour.

**Comment by raysan5** [comment]
@snader feel free to send a PR to add that note in the README.md in `Getting Started with this template`  section.
