### ISSUE TITLE
How to add resources

### ISSUE THREAD

**Issue by loudenvier** [raysan5/raylib-game-template#29]
I'm not a C developer, but I wanted to try to create some games with raylib. This will really be a stupid question, but how can I add resources to the solution? I'm using VS2022 and the provided solution file. I added the files from the Dr. Turtle and Mr. Gamera resources to the src/resources folder, but they are not found when running the game with this warning:

WARNING: FILEIO: [resources/sky.png] Failed to open file
WARNING: FILEIO: [resources/mountains.png] Failed to open file
WARNING: FILEIO: [resources/sea.png] Failed to open file
etc.

Do I have to add all files into a custom build step? What am I missing? 

Note: If I just copy the resources folder to the output folder it works. I notice the CMAKE file have a COPY src/resources command, is it missing in the VS2022 solution? Or does it use another mechanism?

**Comment by WesleyDahar** [comment]
Looks like you have to run the game from the directory containing the resources folder. The resources are loaded relative to the current working directory (CWD).

**Comment by HarryDC** [comment]
A little late but it looks like the template sets a different path to place the binaries than is expected in visual studio, so when you use the "Run" from visual studio the working directory is in the wrong place causing the resources to not be found you can fix this (i'll push a PR later) by adding the following line to cmake 
```
set_property(TARGET ${PROJECT_NAME} PROPERTY VS_DEBUGGER_WORKING_DIRECTORY $<TARGET_FILE_DIR:${PROJECT_NAME}>)
```
Anywhere after line 31, or you can just put `$(TargetDir)` into the projects properties under `Debugging/Working Directory`
