### ISSUE TITLE
Location for resources folder doesn't work with emscripten

### ISSUE THREAD

**Issue by HarryDC** [raysan5/raylib-game-template#35]
After adding `--preload-file resources` emscripten expects the resources file in the working directory rather than the target of the binaries. If you add a path to the name in the `--preload-file` parameter the path is expected to be also used in the actual path used to adress the file (i.e. inside of the c code).  Currently loading calls expect the resources folder to be in the working dir.

**Comment by raysan5** [comment]
@HarryDC Actually, afair, it's possible to map resources to a diferent path for application:
`--preload-file resources@data/assets`
