### ISSUE TITLE
CONVENTIONS omits typedef conventions

### ISSUE THREAD

**Issue by orcmid** [raysan5/raylib-game-template#4]
The **typedef** cases seem to be for title case.  It is not shown, although an already-defined type is used in an example.

I am unclear about the situation with all caps types that also happens in raylib.

The trick around using **struct** declarator names as defined types is also worthy of note.  A mindmeld of the C Language type form :).

E.g.,
```C
typedef struct Texture { ... } Texture

static CoreData CORE = { 0 )
```

**Comment by raysan5** [comment]
@orcmid Yeap, the `typedef struct` convention should be added.

About the all caps variables, those are very special cases: Global variables from structs of structs. I did an exception to notice it and make the code more readable in those special cases. Basically, to easily see functions touching those global states.
