### ISSUE TITLE
Resources not found when running from Visual Studio

### ISSUE THREAD

**Issue by AndrewHamel111** [raysan5/raylib-game-template#42]
Pressing F5 in Visual Studio to build and run the game will cause the resources to not be in the right place (the game is run from `projects/raylib_game` directory) so the user will need to build, then run the .exe from the src folder or copy the resources folder to the specified path each time the resources change.

**Comment by david4shure** [comment]
Having the same issue, not sure how to solve. @AndrewHamel111 idk if you fixed this

**Comment by GSMaxxx** [comment]
check the raylib folder in the path you installed it to. if it has another raylib folder inside, drag the inside one to the previous directory.
